### ISSUE TITLE
Failed to run vllm offline_inference.py with "meta-llama/Llama-2-7b-chat-hf"

### ISSUE THREAD

**Issue by jiafuzha** [intel-analytics/BigDL#9904] opened 2024-01-16 02:20 UTC
```
Exception has occurred: TypeError       (note: full exception trace is shown but execution is paused at: _run_module_as_main)
an integer is required (got type NoneType)
  File "/code-repo/BigDL/python/llm/src/bigdl/llm/vllm/model_executor/models/bigdl_llama.py", line 193, in forward
    bigdl_input_ids = torch.tensor(bigdl_input_ids, device=self.device, dtype=torch.int32)
  File "/root/miniconda3/envs/bigdl-vllm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/bigdl-vllm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/code-repo/BigDL/python/llm/src/bigdl/llm/vllm/worker/worker.py", line 304, in execute_model
    output = self.model(
  File "/root/miniconda3/envs/bigdl-vllm/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/code-repo/BigDL/python/llm/src/bigdl/llm/vllm/engine/llm_engine.py", line 704, in _run_workers
    output = executor(*args, **kwargs)
  File "/code-repo/BigDL/python/llm/src/bigdl/llm/vllm/engine/llm_engine.py", line 555, in step
    output = self._run_workers(
  File "/code-repo/BigDL/python/llm/src/bigdl/llm/vllm/entrypoints/llm.py", line 223, in _run_engine
    step_outputs = self.llm_engine.step()
  File "/code-repo/BigDL/python/llm/src/bigdl/llm/vllm/entrypoints/llm.py", line 202, in generate
    return self._run_engine(use_tqdm)
  File "/code-repo/BigDL/python/llm/example/CPU/vLLM-Serving/offline_inference.py", line 52, in <module>
    outputs = llm.generate(prompts, sampling_params)
  File "/root/miniconda3/envs/bigdl-vllm/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/miniconda3/envs/bigdl-vllm/lib/python3.9/runpy.py", line 197, in _run_module_as_main (Current frame)
    return _run_code(code, main_globals, None,
TypeError: an integer is required (got type NoneType)
```

bigdl_input_ids value is,

[[None, None, 1, 15043, 29892, 590, 1024, 338], [1, 450, 6673, 310, 278, 3303, 3900, 338], [None, None, 1, 450, 7483, 310, 3444, 338], [None, 1, 450, 5434, 310, 319, 29902, 338]].

Whilst in vllm repo, input token is right padded with 0,

tensor([[    1, 15043, 29892,   590,  1024,   338,     0,     0],
        [    1,   450,  6673,   310,   278,  3303,  3900,   338],
        [    1,   450,  7483,   310,  3444,   338,     0,     0]],
       device='cuda:0')

**Comment by gc-fu** [comment] 2024-01-16 07:40
Hi, I cannot reproduce this issue.  I am using bigdl-llm version `2.5.0b20240115`.

Can you check your model files' config file and check the value of "pad_token_id"?  If it does not exist or set to null, please try set it to 0.

Please let me know if the problem still persists or not, thx.

**Comment by jiafuzha** [comment] 2024-01-16 08:46
I am using main branch (commit 0e65385049bae196c278480a56ea22fadc48a1ad). After setting pad_token_id to 0, I still got the same issue. Here is my config.json.

```
(base) [root@sr135 BigDL]#  cat ~/.cache/huggingface/hub/models--meta-llama--Llama-2-7b-chat-hf/snapshots/c1b0db933684edbfe29a06fa47eb19cc48025e93/config.json {
  "_name_or_path": "meta-llama/Llama-2-7b-chat-hf",
  "architectures": [
    "LlamaForCausalLM"
  ],
  "bos_token_id": 1,
  "eos_token_id": 2,
  "pad_token_id": 0,
  "hidden_act": "silu",
  "hidden_size": 4096,
  "initializer_range": 0.02,
  "intermediate_size": 11008,
  "max_position_embeddings": 4096,
  "model_type": "llama",
  "num_attention_heads": 32,
  "num_hidden_layers": 32,
  "num_key_value_heads": 32,
  "pretraining_tp": 1,
  "rms_norm_eps": 1e-05,
  "rope_scaling": null,
  "tie_word_embeddings": false,
  "torch_dtype": "float16",
  "transformers_version": "4.32.0.dev0",
  "use_cache": true,
  "vocab_size": 32000
}
```

**Comment by gc-fu** [comment] 2024-01-16 08:53
Try run `pip3 list | grep bigdl`.  If you install `bigdl-llm` through pip, you probably not use the main branch.

**Comment by jiafuzha** [comment] 2024-01-16 08:56
ok, I'll try your branch later.

**Comment by jiafuzha** [comment] 2024-01-17 03:01
2.5.0b20240115 worked. thanks.

**Comment by gc-fu** [comment] 2024-01-17 08:11
Closed as fixed

**Closed by gc-fu** 2024-01-17 08:11 UTC
Labels: user issue
