### ISSUE TITLE
Memory leak when using quantized model for prediction

### ISSUE THREAD

**Issue by dding3** [intel-analytics/BigDL#2535] opened 2018-05-22 21:13 UTC
The memory consumption grows steadily as multiple inferences running with quantized model. 

After some initial investigation, found the heap memory was actually small and consistent while the used physical memory is steadily increased.

**Comment by jason-dai** [comment] 2018-05-23 02:12
Please provide an example to reproduce the issue.

**Comment by dding3** [comment] 2018-06-13 02:49
Synced with @i8run offline and he has successfully repro this issue.

**Comment by i8run** [comment] 2018-06-13 05:49
User can reproduce it by calling `model.predictImage` multi times. Because of `predictImage` in `AbstractModule` will new `LocalPredictor` every call, which will `cloneModule` multi times. For normal model, the models cloned will be released by GC. But for quantized model, we should released it by manual.

**Closed** 2018-06-28 02:38 UTC
Labels: high priority
