### ISSUE TITLE
Issue of NoSuchMethodError while Training VGGNET on CIFAR-10 dataset

### ISSUE THREAD

**Issue by aayush210789** [intel-analytics/BigDL#1914] opened 2017-11-22 07:09 UTC
Hi, 

I am getting below mentioned error for the following versions :
  
SPARK - 1.6.0
BigDL - 0.3.0
Scala - 2.10

Could you please guide me how to rectify it. Any help or advice is greatly appreciated.
Thanks 

LOG :

spark-submit --master local[*] --driver-memory 5g --class com.intel.analytics.bigdl.
models.vgg.Train dist/lib/bigdl-0.3.0-jar-with-dependencies.jar -f cifar-10-batches-bin -b 256
17/11/21 19:46:14 INFO ThreadPool$: Set mkl threads to 1 on thread 1
17/11/21 19:46:14 INFO Remoting: Starting remoting
17/11/21 19:46:14 INFO Remoting: Remoting started; listening on addresses :[akka.tcp://sparkDriverActorSystem@138.37.37.97:50201]
17/11/21 19:46:14 INFO Remoting: Remoting now listens on addresses: [akka.tcp://sparkDriverActorSystem@138.37.37.97:50201]
17/11/21 19:46:16 INFO Engine$: Auto detect executor number and executor cores number
17/11/21 19:46:16 INFO Engine$: Executor number is 1 and executor cores number is 4
17/11/21 19:46:16 INFO Engine$: Find existing spark context. Checking the spark conf...
17/11/21 19:46:17 INFO DistriOptimizer$: caching training rdd ...
17/11/21 19:46:20 INFO DistriOptimizer$: Cache thread models...
17/11/21 19:46:20 INFO DistriOptimizer$: model thread pool size is 1
2017-11-21 19:46:20 ERROR Executor:95 - Exception in task 0.0 in stage 3.0 (TID 2)
java.lang.NoSuchMethodError: org.apache.spark.storage.BlockManager.putBytes(Lorg/apache/spark/storage/BlockId;Ljava/nio/ByteBuffer;Lorg/apache/spark/storage/StorageLevel;ZLscala/Option;)Lscala/collection/Seq;
    at org.apache.spark.storage.BlockManagerWrapper$.putBytes(BlockManagerWrapper.scala:30)
    at com.intel.analytics.bigdl.parameters.AllReduceParameter.init(AllReduceParameter.scala:154)
    at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$16.apply(DistriOptimizer.scala:574)
    at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$16.apply(DistriOptimizer.scala:546)
    at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
    at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
    at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
    at org.apache.spark.CacheManager.getOrCompute(CacheManager.scala:69)
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:268)
    at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
    at org.apache.spark.scheduler.Task.run(Task.scala:89)
    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:242)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
2017-11-21 19:46:21 ERROR SparkUncaughtExceptionHandler:95 - Uncaught exception in thread Thread[Executor task launch worker-0,5,main]
java.lang.NoSuchMethodError: org.apache.spark.storage.BlockManager.putBytes(Lorg/apache/spark/storage/BlockId;Ljava/nio/ByteBuffer;Lorg/apache/spark/storage/StorageLevel;ZLscala/Option;)Lscala/collection/Seq;
    at org.apache.spark.storage.BlockManagerWrapper$.putBytes(BlockManagerWrapper.scala:30)
    at com.intel.analytics.bigdl.parameters.AllReduceParameter.init(AllReduceParameter.scala:154)
    at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$16.apply(DistriOptimizer.scala:574)
    at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$16.apply(DistriOptimizer.scala:546)
    at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
    at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
    at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
    at org.apache.spark.CacheManager.getOrCompute(CacheManager.scala:69)
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:268)
    at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
    at org.apache.spark.scheduler.Task.run(Task.scala:89)
    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:242)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
2017-11-21 19:46:21 ERROR TaskSetManager:74 - Task 0 in stage 3.0 failed 1 times; aborting job
Exception in thread "main" org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 3.0 failed 1 times, most recent failure: Lost task 0.0 in stage 3.0 (TID 2, localhost, executor driver): java.lang.NoSuchMethodError: org.apache.spark.storage.BlockManager.putBytes(Lorg/apache/spark/storage/BlockId;Ljava/nio/ByteBuffer;Lorg/apache/spark/storage/StorageLevel;ZLscala/Option;)Lscala/collection/Seq;
    at org.apache.spark.storage.BlockManagerWrapper$.putBytes(BlockManagerWrapper.scala:30)
    at com.intel.analytics.bigdl.parameters.AllReduceParameter.init(AllReduceParameter.scala:154)
    at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$16.apply(DistriOptimizer.scala:574)
    at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$16.apply(DistriOptimizer.scala:546)
    at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
    at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
    at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
    at org.apache.spark.CacheManager.getOrCompute(CacheManager.scala:69)
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:268)
    at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
    at org.apache.spark.scheduler.Task.run(Task.scala:89)
    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:242)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

Driver stacktrace:
    at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1457)
    at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1445)
    at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1444)
    at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
    at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
    at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1444)
    at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:799)
    at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:799)
    at scala.Option.foreach(Option.scala:236)
    at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:799)
    at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1668)
    at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1627)
    at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1616)
    at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
    at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:620)
    at org.apache.spark.SparkContext.runJob(SparkContext.scala:1862)
    at org.apache.spark.SparkContext.runJob(SparkContext.scala:1875)
    at org.apache.spark.SparkContext.runJob(SparkContext.scala:1888)
    at org.apache.spark.SparkContext.runJob(SparkContext.scala:1959)
    at org.apache.spark.rdd.RDD.count(RDD.scala:1157)
    at com.intel.analytics.bigdl.optim.DistriOptimizer$.com$intel$analytics$bigdl$optim$DistriOptimizer$$initThreadModels(DistriOptimizer.scala:589)
    at com.intel.analytics.bigdl.optim.DistriOptimizer.optimize(DistriOptimizer.scala:779)
    at com.intel.analytics.bigdl.models.vgg.Train$$anonfun$main$1.apply(Train.scala:80)
    at com.intel.analytics.bigdl.models.vgg.Train$$anonfun$main$1.apply(Train.scala:35)
    at scala.Option.map(Option.scala:145)
    at com.intel.analytics.bigdl.models.vgg.Train$.main(Train.scala:35)
    at com.intel.analytics.bigdl.models.vgg.Train.main(Train.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:730)
    at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
    at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
    at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
    at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.NoSuchMethodError: org.apache.spark.storage.BlockManager.putBytes(Lorg/apache/spark/storage/BlockId;Ljava/nio/ByteBuffer;Lorg/apache/spark/storage/StorageLevel;ZLscala/Option;)Lscala/collection/Seq;
    at org.apache.spark.storage.BlockManagerWrapper$.putBytes(BlockManagerWrapper.scala:30)
    at com.intel.analytics.bigdl.parameters.AllReduceParameter.init(AllReduceParameter.scala:154)
    at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$16.apply(DistriOptimizer.scala:574)
    at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$16.apply(DistriOptimizer.scala:546)
    at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
    at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
    at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
    at org.apache.spark.CacheManager.getOrCompute(CacheManager.scala:69)
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:268)
    at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
    at org.apache.spark.scheduler.Task.run(Task.scala:89)
    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:242)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

**Comment by yiheng** [comment] 2017-11-28 16:21
Hi, I can't reproduce this error. How do you get bigdl? Do you build by yourself? Can you try to use the prebuild version at https://bigdl-project.github.io/master/#release-download/?

**Comment by shane-huang** [comment] 2017-12-07 07:57
NoSuchMethod error often occurs when there's a version mismatch. Please check if you have downloaded the correct version of prebuilt BigDL. If you're using Spark 1.6, you should download the prebuit BigDL jars for Spark 1.6.

**Comment by yiheng** [comment] 2017-12-15 06:14
close this. Please reopen if it's needed.

**Closed by yiheng** 2017-12-15 06:14 UTC
