### ISSUE TITLE
Bark-small load_in_4bit got error

### ISSUE THREAD

**Issue by violet17** [intel-analytics/BigDL#8837] opened 2023-08-29 04:09 UTC
Dear,
Thanks for your great work.

I run bark small(https://huggingface.co/suno/bark-small) on A770， and  get error when using load_in_4bit.
Here are my codes:

```
import torch
from transformers import AutoProcessor
import intel_extension_for_pytorch as ipex
from bigdl.llm.transformers import AutoModel
import scipy
import time

model_path = "./bark-small"
processor = AutoProcessor.from_pretrained(model_path)
model = AutoModel.from_pretrained(model_path,load_in_4bit=True, optimize_model=False)
model = model.to("xpu")

text = "Hello, my name is Suno. And, uh — and I like pizza. [laughs] But I also have other interests such as playing tic tac toe."
t0 = time.time()
with torch.inference_mode():
    inputs = processor(text=[text], return_tensors="pt")
    t1 = time.time()
    print("Cost time--1: ",  t1- t0)
    inputs = inputs.to("xpu")
    speech_values = model.generate(**inputs, do_sample=True)
    print("Cost time--2: ", time.time() - t1)

print("Cost time: ", time.time() - t0)

sampling_rate = model.generation_config.sample_rate
scipy.io.wavfile.write("bark_out.wav", rate=sampling_rate, data=speech_values.cpu().numpy().squeeze())
print("save audio to bark_out.wav---")
```
Running log:
```
$ python bark_bigdl.py 
/home/adc2/miniconda3/envs/llm/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: ''If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
Traceback (most recent call last):
  File "/home/adc2/crystal/llm/bark_bigdl.py", line 13, in <module>
    model = AutoModel.from_pretrained(model_path,load_in_4bit=True, optimize_model=False)
  File "/home/adc2/miniconda3/envs/llm/lib/python3.9/site-packages/bigdl/llm/transformers/model.py", line 82, in from_pretrained
    model = cls.load_convert(q_k, optimize_model, *args, **kwargs)
  File "/home/adc2/miniconda3/envs/llm/lib/python3.9/site-packages/bigdl/llm/transformers/model.py", line 96, in load_convert
    model = cls.HF_Model.from_pretrained(*args, **kwargs)
  File "/home/adc2/miniconda3/envs/llm/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 493, in from_pretrained
    return model_class.from_pretrained(
  File "/home/adc2/miniconda3/envs/llm/lib/python3.9/site-packages/transformers/modeling_utils.py", line 2700, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/home/adc2/miniconda3/envs/llm/lib/python3.9/site-packages/transformers/models/bark/modeling_bark.py", line 1375, in __init__
    self.codec_model = AutoModel.from_config(config.codec_config)
  File "/home/adc2/miniconda3/envs/llm/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 430, in from_config
    return model_class._from_config(config, **kwargs)
  File "/home/adc2/miniconda3/envs/llm/lib/python3.9/site-packages/transformers/modeling_utils.py", line 1142, in _from_config
    model = cls(config, **kwargs)
  File "/home/adc2/miniconda3/envs/llm/lib/python3.9/site-packages/transformers/models/encodec/modeling_encodec.py", line 540, in __init__
    self.encoder = EncodecEncoder(config)
  File "/home/adc2/miniconda3/envs/llm/lib/python3.9/site-packages/transformers/models/encodec/modeling_encodec.py", line 280, in __init__
    model = [EncodecConv1d(config, config.audio_channels, config.num_filters, config.kernel_size)]
  File "/home/adc2/miniconda3/envs/llm/lib/python3.9/site-packages/transformers/models/encodec/modeling_encodec.py", line 114, in __init__
    self.conv = nn.utils.weight_norm(self.conv)
  File "/home/adc2/miniconda3/envs/llm/lib/python3.9/site-packages/torch/nn/utils/weight_norm.py", line 109, in weight_norm
    WeightNorm.apply(module, name, dim)
  File "/home/adc2/miniconda3/envs/llm/lib/python3.9/site-packages/torch/nn/utils/weight_norm.py", line 50, in apply
    setattr(module, name, fn.compute_weight(module))
  File "/home/adc2/miniconda3/envs/llm/lib/python3.9/site-packages/torch/nn/utils/weight_norm.py", line 25, in compute_weight
    return _weight_norm(v, g, self.dim)
NotImplementedError: Could not run 'aten::_weight_norm_interface' with arguments from the 'Meta' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'aten::_weight_norm_interface' is only available for these backends: [CPU, XPU, BackendSelect, Python, FuncTorchDynamicLayerBackMode, Functionalize, Named, Conjugate, Negative, ZeroTensor, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradHIP, AutogradXLA, AutogradMPS, AutogradIPU, AutogradXPU, AutogradHPU, AutogradVE, AutogradLazy, AutogradMeta, AutogradMTIA, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, AutogradNestedTensor, Tracer, AutocastCPU, AutocastXPU, AutocastCUDA, FuncTorchBatched, FuncTorchVmapMode, Batched, VmapMode, FuncTorchGradWrapper, PythonTLSSnapshot, FuncTorchDynamicLayerFrontMode, PythonDispatcher].

CPU: registered at /build/pytorch/build/aten/src/ATen/RegisterCPU.cpp:31034 [kernel]
XPU: registered at /build/intel-pytorch-extension/build/Release/csrc/gpu/csrc/aten/generated/ATen/RegisterXPU.cpp:9929 [kernel]
BackendSelect: fallthrough registered at /build/pytorch/aten/src/ATen/core/BackendSelectFallbackKernel.cpp:3 [backend fallback]
Python: registered at /build/pytorch/aten/src/ATen/core/PythonFallbackKernel.cpp:144 [backend fallback]
FuncTorchDynamicLayerBackMode: registered at /build/pytorch/aten/src/ATen/functorch/DynamicLayer.cpp:491 [backend fallback]
Functionalize: registered at /build/pytorch/aten/src/ATen/FunctionalizeFallbackKernel.cpp:280 [backend fallback]
Named: registered at /build/pytorch/aten/src/ATen/core/NamedRegistrations.cpp:7 [backend fallback]
Conjugate: registered at /build/pytorch/aten/src/ATen/ConjugateFallback.cpp:17 [backend fallback]
Negative: registered at /build/pytorch/aten/src/ATen/native/NegateFallback.cpp:19 [backend fallback]
ZeroTensor: registered at /build/pytorch/aten/src/ATen/ZeroTensorFallback.cpp:86 [backend fallback]
ADInplaceOrView: fallthrough registered at /build/pytorch/aten/src/ATen/core/VariableFallbackKernel.cpp:63 [backend fallback]
AutogradOther: registered at /build/pytorch/torch/csrc/autograd/generated/VariableType_0.cpp:15256 [autograd kernel]
AutogradCPU: registered at /build/pytorch/torch/csrc/autograd/generated/VariableType_0.cpp:15256 [autograd kernel]
AutogradCUDA: registered at /build/pytorch/torch/csrc/autograd/generated/VariableType_0.cpp:15256 [autograd kernel]
AutogradHIP: registered at /build/pytorch/torch/csrc/autograd/generated/VariableType_0.cpp:15256 [autograd kernel]
AutogradXLA: registered at /build/pytorch/torch/csrc/autograd/generated/VariableType_0.cpp:15256 [autograd kernel]
AutogradMPS: registered at /build/pytorch/torch/csrc/autograd/generated/VariableType_0.cpp:15256 [autograd kernel]
AutogradIPU: registered at /build/pytorch/torch/csrc/autograd/generated/VariableType_0.cpp:15256 [autograd kernel]
AutogradXPU: registered at /build/pytorch/torch/csrc/autograd/generated/VariableType_0.cpp:15256 [autograd kernel]
AutogradHPU: registered at /build/pytorch/torch/csrc/autograd/generated/VariableType_0.cpp:15256 [autograd kernel]
AutogradVE: registered at /build/pytorch/torch/csrc/autograd/generated/VariableType_0.cpp:15256 [autograd kernel]
AutogradLazy: registered at /build/pytorch/torch/csrc/autograd/generated/VariableType_0.cpp:15256 [autograd kernel]
AutogradMeta: registered at /build/pytorch/torch/csrc/autograd/generated/VariableType_0.cpp:15256 [autograd kernel]
AutogradMTIA: registered at /build/pytorch/torch/csrc/autograd/generated/VariableType_0.cpp:15256 [autograd kernel]
AutogradPrivateUse1: registered at /build/pytorch/torch/csrc/autograd/generated/VariableType_0.cpp:15256 [autograd kernel]
AutogradPrivateUse2: registered at /build/pytorch/torch/csrc/autograd/generated/VariableType_0.cpp:15256 [autograd kernel]
AutogradPrivateUse3: registered at /build/pytorch/torch/csrc/autograd/generated/VariableType_0.cpp:15256 [autograd kernel]
AutogradNestedTensor: registered at /build/pytorch/torch/csrc/autograd/generated/VariableType_0.cpp:15256 [autograd kernel]
Tracer: registered at /build/pytorch/torch/csrc/autograd/generated/TraceType_0.cpp:16728 [kernel]
AutocastCPU: fallthrough registered at /build/pytorch/aten/src/ATen/autocast_mode.cpp:487 [backend fallback]
AutocastXPU: fallthrough registered at /build/intel-pytorch-extension/csrc/gpu/aten/amp/autocast_mode.cpp:233 [backend fallback]
AutocastCUDA: fallthrough registered at /build/pytorch/aten/src/ATen/autocast_mode.cpp:354 [backend fallback]
FuncTorchBatched: registered at /build/pytorch/aten/src/ATen/functorch/LegacyBatchingRegistrations.cpp:815 [backend fallback]
FuncTorchVmapMode: fallthrough registered at /build/pytorch/aten/src/ATen/functorch/VmapModeRegistrations.cpp:28 [backend fallback]
Batched: registered at /build/pytorch/aten/src/ATen/LegacyBatchingRegistrations.cpp:1073 [backend fallback]
VmapMode: fallthrough registered at /build/pytorch/aten/src/ATen/VmapModeRegistrations.cpp:33 [backend fallback]
FuncTorchGradWrapper: registered at /build/pytorch/aten/src/ATen/functorch/TensorWrapper.cpp:210 [backend fallback]
PythonTLSSnapshot: registered at /build/pytorch/aten/src/ATen/core/PythonFallbackKernel.cpp:152 [backend fallback]
FuncTorchDynamicLayerFrontMode: registered at /build/pytorch/aten/src/ATen/functorch/DynamicLayer.cpp:487 [backend fallback]
PythonDispatcher: registered at /build/pytorch/aten/src/ATen/core/PythonFallbackKernel.cpp:148 [backend fallback]

```

Environment:
i7-12700+A770 ubuntu 22.04，  GPU Driver version 23.17.26241.21

```
(llm) adc2@ADLP-A770:~/crystal/llm$ pip list | grep torch
clip-anytorch               2.5.2
intel-extension-for-pytorch 2.0.110+xpu
torch                       2.0.1a0+cxx11.abi
torchaudio                  2.0.2+31de77d
torchdiffeq                 0.2.3
torchsde                    0.2.5
torchvision                 0.15.2a0+cxx11.abi
(llm) adc2@ADLP-A770:~/crystal/llm$ pip list | grep bigdl
bigdl-core-xe               2.4.0b20230828
bigdl-llm                   2.4.0b20230828
(llm) adc2@ADLP-A770:~/crystal/llm$ uname -r
6.2.0-26-generic
```

Thanks again.

**Comment by jason-dai** [comment] 2023-08-29 04:35
Can the original model run on Arc without BigDL-LLM? Looks like an operator is missing. @leonardozcm please take a look.

**Comment by violet17** [comment] 2023-08-29 05:32
Hi  @jason-dai ,
Yes, the original model can run on Arc with bigdl-llm. I haven't run the original model on Arc with bigdl-llm.
It takes 28s to generate 11s audio on A770， while 46.6s to generate 9s audio using the same input text: text = "Hello, my name is Suno. And, uh — and I like pizza. [laughs] But I also have other interests such as playing tic tac toe."

By the way, `model = model.half().to("xpu")` not works for bark-small.
Erjin told me that bigdl-llm haven't do FP16 optimize so far.

Is there any plan for optimizing bark on Arc?
Thanks.

**Comment by leonardozcm** [comment] 2023-08-29 05:46
hi @violet17, it looks like Bark has some ops not supported by huggingface `low_cpu_mem_usage`  algorithm at fist glance
https://huggingface.co/docs/transformers/main_classes/model#large-model-loading , I will check this.

**Comment by jason-dai** [comment] 2023-08-29 06:56
> hi @violet17, it looks like Bark has some ops not supported by huggingface `low_cpu_mem_usage` algorithm at fist glance https://huggingface.co/docs/transformers/main_classes/model#large-model-loading , I will check this.

I think we can first add an argument that allows users to disable huggingface `low_cpu_mem_usage` when loading the model

**Comment by leonardozcm** [comment] 2023-08-29 07:04
By remove this line, I success in a generated audio.
https://github.com/intel-analytics/BigDL/blob/main/python/llm/src/bigdl/llm/transformers/model.py#L80

And don't worry about memory usage, it is only 1.5GB of bark-small, it will take at most 3~4GB peak memory to load in 4 bit.

> I think we can first add an argument that allows users to disable huggingface `low_cpu_mem_usage` when loading the model

We may add an argument to achieve this.

Following are the reasons why low_cpu_mem_usage won't work:

We are enforcing the experimental feature "low_cpu_mem_usage" to alleviate memory pressure when loading large models. This feature avoids initializing the parameters when initializing empty model itself (by put everything on a meta device). However, the bark contains a operation named "weights_norm" , which normalizes the weights during initialization, necessitating non-empty weights. This conflicts with the design of the meta device, and this is why "low_cpu_mem_usage" doesn't work on bark.

**Comment by leonardozcm** [comment] 2023-08-29 07:08
> I think we can first add an argument that allows users to disable huggingface `low_cpu_mem_usage` when loading the model

Or may we make this process more more automated?
For example, by first loading with "low_mem_cpu_usage", if an exception is caught, then proceed to handle it using the original loading method.

**Comment by jason-dai** [comment] 2023-08-29 07:18
> Or may we make this process more more automated? I suppose users may not realize when to specify `low_cpu_mem_usage`. For example, by first loading with "low_mem_cpu_usage", if an exception is caught, then proceed to handle it using the original loading method.

Sure, we can do that.

**Comment by leonardozcm** [comment] 2023-09-13 08:08
Seems like a performance issue, would you mind taking a look at this? @rnwang04

**Comment by rnwang04** [comment] 2023-09-14 01:11
I have found the root cause of this error and raised a pr to fix it, it will be merged today.
@violet17 You can pip install latest version(2.4.0b20230914) tomorrow and try it again.

**Comment by violet17** [comment] 2023-09-14 01:16
@rnwang04  Hi ，thanks for your reply. I will try it tomorrow.

**Closed** 2023-09-14 01:39 UTC
Labels: user issue

**Comment by violet17** [comment] 2023-09-20 05:43
@rnwang04  I have tried  2.4.0b20230919 version. It can run.
However, the generated audio is not correct, which is noise.
