### ISSUE TITLE
MKL-DNN will modify the model when doing inference

### ISSUE THREAD

**Issue by Menooker** [intel-analytics/BigDL#2838] opened 2019-06-13 08:47 UTC
When doing inference using mkl-dnn engine, the weights of the model may be modified by the engine. It seems that the `forward` operation will call `initFwdPrimitives` that will do fusion operations. And the fusion operation will do in-place modifications on the model weights. However,  a model may call "forward" for multiple times, which will corrupt the model.

**Comment by qiuxin2012** [comment] 2019-06-14 05:48
If the model is corrupted, will the result be Nan?

**Comment by Menooker** [comment] 2019-06-14 07:15
@qiuxin2012 No, the forward output will be finite, but not correct. In my case, the corrupted model (Resnet-50, 2 classes) will always get "positive" result, but the scores for the both classes are finite. The problem only appears when using a IRGraph model.

**Comment by qiuxin2012** [comment] 2019-06-14 08:14
@Menooker In my case...I got NaN...
As cherry told me a way to work around this issue. broadcast the model, and call `.value()` to cache the model, then calling the cached model's `forward` multi times won't invoke this issue. Is it right?

**Comment by Menooker** [comment] 2019-06-14 08:25
@qiuxin2012 In my application, this will corrupt the model. That's how I found this issue (load model from file => toIRGraph() => broadcast the model => MyPredictor.predictImage(localCachedModel) for multiple times => corrupted model)

**Comment by Menooker** [comment] 2019-06-14 08:38
@qiuxin2012 @zhangxiaoli73 Hi, I have composed a simple program to reproduce the problem.

The program uses Resnet model and prints the sum of the weights to check if the model is modified.

Note: I found that if I remove `.evaluate()` in the line ` val bcast = ModelBroadcast[Float](....` the model will be unchanged.

```scala
import com.intel.analytics.bigdl.mkl.Memory
import com.intel.analytics.bigdl.models.utils.ModelBroadcast
import com.intel.analytics.bigdl.nn.abstractnn.{AbstractModule, Activity}
import com.intel.analytics.bigdl.nn.{Linear, Module, ReLU, Sequential, StaticGraph}
import com.intel.analytics.bigdl.tensor.Tensor
import com.intel.analytics.bigdl.utils.{Engine, LoggerFilter}
import org.apache.spark.SparkContext
import com.intel.analytics.bigdl.tensor.TensorNumericMath.TensorNumeric

object tester {
  LoggerFilter.redirectSparkInfoLogs()
  def main(argv: Array[String]): Unit ={
    val conf = Engine.createSparkConf().setAppName("Predict ResNet")
      .set("spark.rpc.message.maxSize", "200")
    val sc = new SparkContext(conf)
    Engine.init

    val module = Module.loadModule[Float]("/home/menooker/IdeaProjects/MKL_DNN2.obj").asInstanceOf[StaticGraph[Float]]
      .toIRgraph()
    //val module = m.toGraph().asInstanceOf[StaticGraph[Float]]

    println(s"Orig ${module.getWeightsBias().map(f=>f.sum()).sum}")
    val bcast = ModelBroadcast[Float]().broadcast(sc, module.evaluate())
    for(i <- 1 to 3){
      val data = sc.parallelize(0 to 10,1)
      data.mapPartitions(i=>{
        val tensor = Tensor[Float](10,3, 224,224).rand()
        val mod = bcast.value()

        //val v1 = tensor.valueAt(1)
        //val v2 = tensor.valueAt(2)
        Iterator(mod.forward(tensor).toTensor[Float])
      }).map(t=>{
        ("1",t)
      }).reduceByKey(_+_).collect()

      sc.parallelize(1 to 1, 1).mapPartitions( i=>{
        println(s"${bcast.value().getWeightsBias().map(f=>f.sum()).sum}")
        i
      }).count()
    }

  }
}

```

**Comment by zhangxiaoli73** [comment] 2019-06-17 00:31
@Menooker Yes, this issue is caused by model fusion, and fusion will be done only for model inference.

**Comment by qiuxin2012** [comment] 2019-06-17 01:12
@Menooker If you remove the `.evalute()`, will result changed in the second forward for the same input? 
In my opinion, if you don't call `evalute()`, the batchnormlization will be in training mode, so the running mean and running var will be changed in every forward, the output is incorrect then.

**Comment by Menooker** [comment] 2019-06-17 01:39
> @Menooker If you remove the `.evalute()`, will result changed in the second forward for the same input?

Yes, after removing it, the result will be changed.

**Closed** 2019-06-17 07:09 UTC
