### ISSUE TITLE
Pytorch example notebook does not work on Databricks with big DL 

### ISSUE THREAD

**Issue by vidit-bhatia** [intel-analytics/BigDL#8813] opened 2023-08-25 12:12 UTC
Hi I followed the documentation given here 
https://github.com/sgwhat/BigDL/blob/main/docs/readthedocs/source/doc/UserGuide/databricks.md to setup my databricks cluster I am able to run keras/ tensorflow code but torch code is giving the following error

`Py4JJavaError                             Traceback (most recent call last)
<command-2862489893277747> in <module>
----> 1 stats = est.fit(train_data, 
      2                 epochs=epochs,
      3                 batch_size=batch_size,
      4                 feature_cols=['user', 'item'], # specifies which column(s) to be used as inputs
      5                 label_cols=['label'], # specifies which column(s) to be used as labels

/databricks/python/lib/python3.8/site-packages/bigdl/orca/learn/pytorch/pytorch_pyspark_estimator.py in fit(self, data, epochs, max_steps, batch_size, profile, reduce_results, feature_cols, label_cols, validation_data, callbacks)
    334 
    335                 data_rdd = data.rdd  # type:ignore
--> 336                 res = data_rdd.barrier().mapPartitions(
    337                     lambda iter: transform_func(iter, init_params, params)).collect()
    338 

/databricks/spark/python/pyspark/rdd.py in collect(self)
    964         # Default path used in OSS Spark / for non-credential passthrough clusters:
    965         with SCCallSiteSync(self.context) as css:
--> 966             sock_info = self.ctx._jvm.PythonRDD.collectAndServe(self._jrdd.rdd())
    967         return list(_load_from_socket(sock_info, self._jrdd_deserializer))
    968 

/databricks/spark/python/lib/py4j-0.10.9.1-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1302 
   1303         answer = self.gateway_client.send_command(command)
-> 1304         return_value = get_return_value(
   1305             answer, self.gateway_client, self.target_id, self.name)
   1306 

/databricks/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
    115     def deco(*a, **kw):
    116         try:
--> 117             return f(*a, **kw)
    118         except py4j.protocol.Py4JJavaError as e:
    119             converted = convert_exception(e.java_exception)

/databricks/spark/python/lib/py4j-0.10.9.1-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    324             value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
    325             if answer[1] == REFERENCE_TYPE:
--> 326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
    328                     format(target_id, ".", name), value)

Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.collectAndServe.
: org.apache.spark.SparkException: Job aborted due to stage failure: Could not recover from a failed barrier ResultStage. Most recent failure reason: Stage failed because barrier task ResultTask(24, 0) finished unsuccessfully.
org.apache.spark.api.python.PythonException: 'RuntimeError: [../third_party/gloo/gloo/transport/tcp/pair.cc:799] connect [127.0.1.1]:34702: Connection refused'. Full traceback below:
Traceback (most recent call last):
  File "/databricks/spark/python/pyspark/worker.py", line 770, in main
    process()
  File "/databricks/spark/python/pyspark/worker.py", line 760, in process
    out_iter = func(split_index, iterator)
  File "/databricks/spark/python/pyspark/rdd.py", line 2952, in pipeline_func
    return func(split, prev_func(split, iterator))
  File "/databricks/spark/python/pyspark/rdd.py", line 2899, in func
    return f(iterator)
  File "/databricks/python/lib/python3.8/site-packages/bigdl/orca/learn/pytorch/pytorch_pyspark_estimator.py", line 337, in <lambda>
    lambda iter: transform_func(iter, init_params, params)).collect()
  File "/databricks/python/lib/python3.8/site-packages/bigdl/orca/learn/pytorch/pytorch_pyspark_estimator.py", line 330, in transform_func
    runner = PytorchPysparkWorker(**init_params)
  File "/databricks/python/lib/python3.8/site-packages/bigdl/orca/learn/pytorch/pytorch_pyspark_worker.py", line 93, in __init__
    self.setup_distributed(self.mode, cluster_info, driver_ip, driver_tcp_store_port)
  File "/databricks/python/lib/python3.8/site-packages/bigdl/orca/learn/pytorch/pytorch_pyspark_worker.py", line 116, in setup_distributed
    self.setup_torch_distribute(tcp_store_host=driver_ip,
  File "/databricks/python/lib/python3.8/site-packages/bigdl/orca/learn/pytorch/core/lifecycle.py", line 29, in setup_torch_distribute
    self._init_torch_ddp(tcp_store_host, tcp_store_port, world_rank,
  File "/databricks/python/lib/python3.8/site-packages/bigdl/orca/learn/pytorch/core/lifecycle.py", line 72, in _init_torch_ddp
    dist.init_process_group(
  File "/databricks/python/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 602, in init_process_group
    default_pg = _new_process_group_helper(
  File "/databricks/python/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 703, in _new_process_group_helper
    pg = ProcessGroupGloo(prefix_store, rank, world_size, timeout=timeout)
RuntimeError: [../third_party/gloo/gloo/transport/tcp/pair.cc:799] connect [127.0.1.1]:34702: Connection refused

	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.handlePythonException(PythonRunner.scala:694)
	at org.apache.spark.api.python.PythonRunner$$anon$3.read(PythonRunner.scala:904)
	at org.apache.spark.api.python.PythonRunner$$anon$3.read(PythonRunner.scala:886)
	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.hasNext(PythonRunner.scala:647)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at org.apache.spark.InterruptibleIterator.foreach(InterruptibleIterator.scala:28)
	at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:62)
	at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:53)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:105)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:49)
	at scala.collection.TraversableOnce.to(TraversableOnce.scala:366)
	at scala.collection.TraversableOnce.to$(TraversableOnce.scala:364)
	at org.apache.spark.InterruptibleIterator.to(InterruptibleIterator.scala:28)
	at scala.collection.TraversableOnce.toBuffer(TraversableOnce.scala:358)
	at scala.collection.TraversableOnce.toBuffer$(TraversableOnce.scala:358)
	at org.apache.spark.InterruptibleIterator.toBuffer(InterruptibleIterator.scala:28)
	at scala.collection.TraversableOnce.toArray(TraversableOnce.scala:345)
	at scala.collection.TraversableOnce.toArray$(TraversableOnce.scala:339)
	at org.apache.spark.InterruptibleIterator.toArray(InterruptibleIterator.scala:28)
	at org.apache.spark.rdd.RDD.$anonfun$collect$2(RDD.scala:1038)
	at org.apache.spark.scheduler.ResultTask.$anonfun$runTask$3(ResultTask.scala:75)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.ResultTask.$anonfun$runTask$1(ResultTask.scala:75)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:55)
	at org.apache.spark.scheduler.Task.doRunTask(Task.scala:156)
	at org.apache.spark.scheduler.Task.$anonfun$run$1(Task.scala:125)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.Task.run(Task.scala:95)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$13(Executor.scala:832)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1681)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:835)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:690)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:3088)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:3035)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:3029)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:3029)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskCompletion(DAGScheduler.scala:2662)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:3294)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:3238)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:3226)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:1157)
	at org.apache.spark.SparkContext.runJobInternal(SparkContext.scala:2657)
	at org.apache.spark.rdd.RDD.$anonfun$collect$1(RDD.scala:1036)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:165)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:125)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:419)
	at org.apache.spark.rdd.RDD.collect(RDD.scala:1034)
	at org.apache.spark.api.python.PythonRDD$.collectAndServe(PythonRDD.scala:260)
	at org.apache.spark.api.python.PythonRDD.collectAndServe(PythonRDD.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
	at py4j.Gateway.invoke(Gateway.java:295)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:251)
	at java.lang.Thread.run(Thread.java:750)`

I have tried multiple combinations. 
This is my current version and init.sh file as given in the user guide

`
# install bigdl-orca, add other bigdl modules if you need
/databricks/python/bin/pip install pip install --upgrade bigdl-orca-spark3[ray]

# install other necessary libraries, here we install libraries needed in this tutorial
/databricks/python/bin/pip install tensorflow==2.9.1
/databricks/python/bin/pip install tqdm
/databricks/python/bin/pip install torch==1.11.0+cpu torchvision==0.12.0+cpu tensorboard -f https://download.pytorch.org/whl/torch_stable.html

# copy bigdl jars to databricks
cp /databricks/python/lib/python3.8/site-packages/bigdl/share/*/lib/*.jar /databricks/jars`

I can attach my notebook but it is not letting me do it

**Comment by jason-dai** [comment] 2023-08-25 12:23
@jenniew please take a look

**Comment by sgwhat** [comment] 2023-08-28 05:42
Hi, Vidit Bhatia!

After our testing, the PyTorch Estimator could run successfully on the Local Client. We suspect the issue might be related to PyTorch creating a DDP Process Group on the Databricks cluster. Of course, we will continue testing and resolving the problem on Databricks very soon. 

By the way, perhaps you could try running the PyTorch examples on your local machine in the meantime? 😄

**Comment by jenniew** [comment] 2023-08-28 21:11
@vidit-bhatia We have reproduced your issue in our Databricks cluster environment. We'll figure it out and resolve this issue soon. Will keep you posted.

**Comment by vidit-bhatia** [comment] 2023-08-29 06:18
@jenniew thanks for working on this and reproducing the issue.

**Comment by sgwhat** [comment] 2023-08-29 08:50
> @vidit-bhatia We have reproduced your issue in our Databricks cluster environment. We'll figure it out and resolve this issue soon. Will keep you posted.

Does ray backend work fine on Databricks? Also, we may check if `get_node_ip` could return the correct driver ip address.

**Comment by jenniew** [comment] 2023-08-30 02:30
I found the reason is that on each Databricks node, the ip for hostname is set to 127.0.1.1, and gloo just use hostname's ip(127.0.1.1) of each node to create process group which arise this issue. You can set GLOO_SOCKET_IFNAME="eth0" in cluster's configuration to let gloo use correct interface to create process group. And we'll update the corresponding documents.

**Comment by vidit-bhatia** [comment] 2023-08-30 14:09
@jenniew I can confirm that this change is working I added GLOO_SOCKET_IFNAME="eth0" in the environment variables. If required I can create a PR for this in the documentation but I confirm the fix worked.

**Comment by vidit-bhatia** [comment] 2023-08-30 14:10
<img width="832" alt="Screenshot 2023-08-30 at 7 40 07 PM" src="https://github.com/intel-analytics/BigDL/assets/3845645/147f36fa-d011-4586-8935-2dfebba6b960">
This was the exact change made

**Comment by jenniew** [comment] 2023-09-01 19:12
@vidit-bhatia I create a PR (https://github.com/intel-analytics/BigDL/pull/8869) for the document change. You can help to review it.

**Closed** 2023-09-06 11:48 UTC
Labels: orca, user issue
