### ISSUE TITLE
Error when load models from Keras

### ISSUE THREAD

**Issue by Thesharing** [intel-analytics/BigDL#2041] opened 2017-12-17 15:09 UTC
When I run the example of [BigDL/pyspark/bigdl/examples/keras/cnn.py](https://github.com/intel-analytics/BigDL/blob/master/pyspark/bigdl/examples/keras/cnn.py), there is an error when loading the model from Keras:

> Traceback (most recent call last):
>   File "/root/hadoop/cloud-computing-homework/bigdl_cnn.py", line 95, in <module>
>     bigdl_model = Model.load_keras(def_path=def_path)
>   File "/usr/local/bigdl/dist/lib/bigdl-0.4.0-SNAPSHOT-python-api.zip/bigdl/nn/layer.py", line 740, in load_keras
>   File "/usr/local/bigdl/dist/lib/bigdl-0.4.0-SNAPSHOT-python-api.zip/bigdl/keras/converter.py", line 345, in from_json_path
>   File "/usr/local/bigdl/dist/lib/bigdl-0.4.0-SNAPSHOT-python-api.zip/bigdl/keras/converter.py", line 350, in from_json_str
>   File "/usr/local/bigdl/dist/lib/bigdl-0.4.0-SNAPSHOT-python-api.zip/bigdl/keras/converter.py", line 336, in from_kmodel
>   File "/usr/local/bigdl/dist/lib/bigdl-0.4.0-SNAPSHOT-python-api.zip/bigdl/keras/converter.py", line 324, in __to_bigdl
>   File "/usr/local/bigdl/dist/lib/bigdl-0.4.0-SNAPSHOT-python-api.zip/bigdl/keras/converter.py", line 393, in _construct_bigdl_sequence
>   File "/usr/local/bigdl/dist/lib/bigdl-0.4.0-SNAPSHOT-python-api.zip/bigdl/keras/converter.py", line 458, in create
>   File "/usr/local/bigdl/dist/lib/bigdl-0.4.0-SNAPSHOT-python-api.zip/bigdl/keras/converter.py", line 480, in create_dense
> KeyError: 'output_dim'

And then I print the keys in `self.config` of function `create_dense` in class `LayerConverter` from [BigDL/pyspark/bigdl/keras/converter.py](https://github.com/intel-analytics/BigDL/blob/master/pyspark/bigdl/keras/converter.py) and I get:
> dict_keys(['name', 'trainable', 'batch_input_shape', 'dtype', 'units', 'activation', 'use_bias', 'kernel_initializer', 'bias_initializer', 'kernel_regularizer', 'bias_regularizer', 'activity_regularizer', 'kernel_constraint', 'bias_constraint'])

It feels like there is no `output_dim` in `self.config`, how can I fix it?

Also in this example, I found that the function `save_keras_model` will try to save the json file of Keras model in local file system, but the function `load_keras` will try to load the json file of Keras model from HDFS. So when I run the example, I meet the error:

> py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.collectAndServe.
: org.apache.hadoop.mapred.InvalidInputException: Input path does not exist: hdfs://master:9000/tmp/lenet.json

Can you fix it?

**Comment by hkvision** [comment] 2017-12-18 01:05
Hi, for the first question, we state here https://github.com/intel-analytics/BigDL/blob/master/docs/docs/ProgrammingGuide/keras-support.md that the keras version we support is __Keras 1.2.2__. I think you are using the latest version of Keras and causes this problem. You can try to use 1.2.2 and there's `output_dim` in `dense`: https://faroit.github.io/keras-docs/1.2.2/layers/core/#dense

**Comment by hkvision** [comment] 2017-12-18 01:11
For the second question, when I run this example on my machine, the json file is stored in local file system. And when loading the model, if you don't specify `hdfs://` or other file system paths, the file should be loaded from local file system. Thus, it is strange that it loads by default from HDFS. Can you try saving the file in another local location like `/home/xxx/...` and rerun the program? Feel free to tell us if the file is still loaded from HDFS.

**Comment by hkvision** [comment] 2017-12-18 01:13
@Thesharing Thanks for the points you raised and your feedback!

**Comment by hkvision** [comment] 2017-12-20 01:36
@Thesharing Hi Zhilong, have your problems been resolved? Your feedback is important to us! :)

**Comment by Thesharing** [comment] 2017-12-20 03:25
@hkvision Really grateful for your detailed reply! 

First I find that the example of BigDL/pyspark/bigdl/examples/keras/cnn.py has been changed to [BigDL/pyspark/bigdl/examples/keras/keras_utils.py](https://github.com/intel-analytics/BigDL/blob/master/pyspark/bigdl/examples/keras/keras_utils.py), so I pull the newest codes and update the python API library on my computer.
Then I run the code on spark (local[8]) and got the error:

> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
>   File "/root/hadoop/bigdl_keras_cnn.py", line 69, in <module>
>     keras_model = build_keras_model()
>   File "/root/hadoop/bigdl_keras_cnn.py", line 53, in build_keras_model
>     input_shape=(1, 28, 28)))
>   File "/root/anaconda3/lib/python3.6/site-packages/keras/models.py", line 299, in add
>     layer.create_input_layer(batch_input_shape, input_dtype)
>   File "/root/anaconda3/lib/python3.6/site-packages/keras/engine/topology.py", line 401, in create_input_layer
>     self(x)
>   File "/root/anaconda3/lib/python3.6/site-packages/keras/engine/topology.py", line 572, in __call__
>     self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
>   File "/root/anaconda3/lib/python3.6/site-packages/keras/engine/topology.py", line 635, in add_inbound_node
>     Node.create_node(self, inbound_layers, node_indices, tensor_indices)
>   File "/root/anaconda3/lib/python3.6/site-packages/keras/engine/topology.py", line 166, in create_node
>     output_tensors = to_list(outbound_layer.call(input_tensors[0], mask=input_masks[0]))
>   File "/root/anaconda3/lib/python3.6/site-packages/keras/layers/convolutional.py", line 475, in call
>     filter_shape=self.W_shape)
>   File "/root/anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2691, in conv2d
>     x = tf.nn.conv2d(x, kernel, strides, padding=padding)
>   File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 631, in conv2d
>     data_format=data_format, name=name)
>   File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
>     op_def=op_def)
>   File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2958, in create_op
>     set_shapes_for_outputs(ret)
>   File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2209, in set_shapes_for_outputs
>     shapes = shape_func(op)
>   File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2159, in call_with_requiring
>     return call_cpp_shape_fn(op, require_shape_fn=True)
>   File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/common_shapes.py", line 627, in call_cpp_shape_fn
>     require_shape_fn)
>   File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/common_shapes.py", line 691, in _call_cpp_shape_fn_impl
>     raise ValueError(err.message)
> ValueError: Negative dimension size caused by subtracting 3 from 1 for 'Conv2D' (op: 'Conv2D') with input shapes: [?,1,28,28], [3,3,28,32].

So I wonder if 
```python
images = images.reshape(images.shape[0], 1, 28, 28)
```
in line 34 should be changed to 
```python
images = images.reshape(images.shape[0], 28, 28, 1)
``` 
and correspondingly 
```python
keras_model.add(Convolution2D(32, 3, 3, border_mode='valid',
                                  input_shape=(1, 28, 28)))
```
should be changed to
```python
keras_model.add(Convolution2D(32, 3, 3, border_mode='valid',
                                  input_shape=(28, 28, 1)))
```

Second, I change `json_path = "/tmp/lenet.json"` in the line 70 to `json_path = "/usr/local/lenet.json"` and I get the error:

> py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.collectAndServe.
> : org.apache.hadoop.mapred.InvalidInputException: Input path does not exist: hdfs://master:9000/usr/local/lenet.json

So I think change the path doesn't work.

**Comment by hkvision** [comment] 2017-12-20 03:34
@Thesharing Hi Zhilong, thank you for your feedback!
First of all `cnn.py` has now been renamed to `minst_cnn.py` and `keras_utils.py` just contains some utility functions.
For the shape error, I forget to mention that BigDL supports `dim_ordering='th'` and I primary test use `th`. Thus if you change the default `dim_ordering` in `~/.keras/keras.json` to `th` (it is by default to be `tf` if you never set it), this problem should be resolved.

**Comment by hkvision** [comment] 2017-12-20 03:41
One of the reasons why we focus on `Keras 1.2.2` is that 1.2.2 is stable and some of the pre-trained Keras models are written in Keras 1.x.

**Comment by hkvision** [comment] 2017-12-20 03:44
@Thesharing How do you run the example? Use `spark-submit`? Can you try running with `python minst_cnn.py` in terminal or running in IDE? I have tested by running in PyCharm and the paths are all local. If you use `spark-submit`, can you give me the command so that I can try and see if I can reproduce the problem? Thanks!

**Comment by Thesharing** [comment] 2017-12-20 04:01
@hkvision Thanks for your immediate reply :+1: 

Part 1

I wonder if the example could take care of both situations about `dim_ordering` like the example of keras do ([keras/examples/mnist_cnn.py](https://github.com/keras-team/keras/blob/master/examples/mnist_cnn.py), but this example is based on 2.1.2, I'm not sure whether this works on 1.2.2...):

```
if K.image_data_format() == 'channels_first':
    x_train = x_train.reshape(x_train.shape[0], 1, img_rows, img_cols)
    x_test = x_test.reshape(x_test.shape[0], 1, img_rows, img_cols)
    input_shape = (1, img_rows, img_cols)
else:
    x_train = x_train.reshape(x_train.shape[0], img_rows, img_cols, 1)
    x_test = x_test.reshape(x_test.shape[0], img_rows, img_cols, 1)
    input_shape = (img_rows, img_cols, 1)
```

(I'm a green hand for both Keras and BigDL, so it would be great if you don't mind pointing out my errors.)

Part 2

I run the code in the docker. First I start up the docker, which contains hadoop, spark, keras and BigDL. I run the hadoop and spark with local mode, then I use `spark-submit` to run the example:

(The command is from [BigDL/pyspark/bigdl/models/lenet/](https://github.com/intel-analytics/BigDL/tree/master/pyspark/bigdl/models/lenet). I can run that code and get the right result.)

```bash
${SPARK_HOME}/bin/spark-submit \
        --master local[*] \
        --driver-memory 4g  \
        --executor-cores 8  \
        --executor-memory 4g \
        --py-files ${PYTHON_API_ZIP_PATH},/root/hadoop/bigdl_keras_cnn.py  \
        --properties-file ${BigDL_HOME}/dist/conf/spark-bigdl.conf \
        --jars ${BigDL_JAR_PATH} \
        --conf spark.driver.extraClassPath=${BigDL_JAR_PATH} \
        --conf spark.executor.extraClassPath=bigdl-SPARK_2.2-0.4.0-SNAPSHOT-jar-with-dependencies.jar \
        /root/hadoop/bigdl_keras_cnn.py \
        --action train \
        --dataPath /tmp/mnist
```

I barely modify the code except the `json_path` and the shape of input.

Part 3

I run the code with `python` command directly and I get the error:

> 17/12/20 03:53:45 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
> Traceback (most recent call last):
>   File "/root/hadoop/bigdl_keras_cnn.py", line 74, in <module>
>     from bigdl.nn.layer import *
>   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
>   File "/usr/local/bigdl/dist/lib/bigdl-0.4.0-SNAPSHOT-python-api.zip/bigdl/nn/layer.py", line 31, in <module>
>   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
>   File "/usr/local/bigdl/dist/lib/bigdl-0.4.0-SNAPSHOT-python-api.zip/bigdl/optim/optimizer.py", line 634, in <module>
>   File "/usr/local/bigdl/dist/lib/bigdl-0.4.0-SNAPSHOT-python-api.zip/bigdl/optim/optimizer.py", line 671, in Optimizer
>   File "/usr/local/bigdl/dist/lib/bigdl-0.4.0-SNAPSHOT-python-api.zip/bigdl/optim/optimizer.py", line 140, in __init__
>   File "/usr/local/bigdl/dist/lib/bigdl-0.4.0-SNAPSHOT-python-api.zip/bigdl/util/common.py", line 88, in __init__
>   File "/usr/local/bigdl/dist/lib/bigdl-0.4.0-SNAPSHOT-python-api.zip/bigdl/util/common.py", line 511, in callBigDlFunc
>   File "/usr/local/bigdl/dist/lib/bigdl-0.4.0-SNAPSHOT-python-api.zip/bigdl/util/common.py", line 52, in instance
>   File "/usr/local/bigdl/dist/lib/bigdl-0.4.0-SNAPSHOT-python-api.zip/bigdl/util/common.py", line 73, in __init__
> TypeError: 'JavaPackage' object is not callable

Do I miss any environment variables?

**Comment by hkvision** [comment] 2017-12-20 05:22
@Thesharing For Part 3, it seems that the jar file can't be found.
Try running `source BigDL/pyspark/test/dev/prepare_env.sh` first. It will help you set `BIGDL_CLASSPATH`. Tell me if you still face the problem.
For Part 1, thank you for the point you raise. Let me have a look whether I can do this, which should not be difficult. For Part 2, let me try the command you use and see what's happening. I'll get back to you soon!
Keras is the newly added feature in the new release and we really appreciate that you try out the example and point out the potential problems! Thanks so much!

**Comment by hkvision** [comment] 2017-12-20 09:06
#2072 This PR has been created to solve the input_shape problem @Thesharing Thanks so much!

**Comment by hkvision** [comment] 2017-12-20 11:40
@Thesharing Hi, Zhilong,
For Part 3, if you run the code with `python`, you can do the following which I tried just now and ran successfully:
```
source BigDL/pyspark/test/dev/prepare_env.sh
python BigDL/pyspark/bigdl/examples/keras/mnist_cnn.py
```

For Part 2, I tested locally on my computer using `spark-submit` and similar command from the `lenet` example, I didn't reproduce the error you got.
I'm not sure if running in docker will make things different. The path by default if you don't specify something like `hdfs`, it will be treated as a local path. So, it is weird that you got this error.
Can you just run the code not using the docker and have a try using `spark-submit`?

You can first try the way I suggest in Part 3. We can have more discussion if you still face the problem. 
For the shape problem, the PR is to be merged very soon. Before that, you may first change the shape to (28, 28, 1) as you do or change `dim_ordering` in the config file.
It will be great if you can let me know your updates for running this example. Thanks so much!

**Comment by hkvision** [comment] 2017-12-21 03:37
@Thesharing Hi, Zhilong,
For the path error, maybe there's some config that leads to search in hdfs instead of local fs?
Can you try replace the load module line with the following:
```
bigdl_model = Model.load_keras(json_path="file:///tmp/lenet.json")
```
`file:///` may force the path to be a local path.
If you have any update, feel free to tell me! Feedbacks from you is important to us! Thanks!

**Comment by hkvision** [comment] 2017-12-21 04:28
#2072 merged. The `input_shape` won't be a problem for both `th` and `tf` `dim_ordering`. And I add some instructions in README file on how to run the examples. @Thesharing

**Comment by hkvision** [comment] 2017-12-25 01:25
@Thesharing Any update? Do you still face the problem of running this example?

**Comment by hkvision** [comment] 2017-12-28 01:33
@Thesharing Hi Zhilong, not sure if you have successfully run this example or not. I first close this issue for now. If you have more problems when using BigDL and Keras, you can open another issue or directly send me a message and I'm very glad to help. Thanks for using BigDL and giving us feedback!

**Closed by hkvision** 2017-12-28 01:33 UTC
Labels: Keras support, model loading
