### ISSUE TITLE
Failed to enable AMX

### ISSUE THREAD

**Issue by sriraman2020** [intel-analytics/BigDL#9978] opened 2024-01-23 13:35 UTC
Trying out Mixtral on PVC-1Card-1Tile with recipe from 
https://github.com/intel-analytics/BigDL/tree/main/python/llm/example/GPU/HF-Transformers-AutoModels/Model/mixtral

command line:
python ./generate.py --prompt 'what is AI?' --repo-id-or -model-path mistralai/Mixtral-8x7B-v0.1

Get this error "Failed to  enable AMX"
Any suggestions pls.

**Comment by jason-dai** [comment] 2024-01-23 13:42
@jenniew please take a look

**Comment by jenniew** [comment] 2024-01-23 23:25
@sriraman2020 I tried this on my pvc, and didn't reproduce this issue. I think this may be your environment issue. Can you run ` source /opt/intel/oneapi/setvars.sh` before running this example?

**Comment by sriraman2020** [comment] 2024-01-24 03:54
<img width="794" alt="image" src="https://github.com/intel-analytics/BigDL/assets/75805404/bd9fb581-b908-4cb1-a58a-db09e2640602">
@jenniew

**Comment by hkvision** [comment] 2024-01-24 07:47
Hi @sriraman2020 

We again confirmed in our environment, we can't reproduce this issue. Somehow AMX fails to get enabled on your SPR, wondering is there anything special to your SPR?

As a workaround, you may use `export BIGDL_LLM_AMX_DISABLED=1` to disable AMX to see if you can proceed.

**Comment by sriraman2020** [comment] 2024-01-24 08:11
@hkvision i tried with the above option. it moves ahead.
But stuck with next error
**ImportError: libsycl.so.6: cannot  open shared object file: No such file or directory**

**Comment by hkvision** [comment] 2024-01-24 08:43
Check this page for your error: https://bigdl.readthedocs.io/en/latest/doc/LLM/Overview/install_gpu.html#cannot-open-shared-object-file-no-such-file-or-directory
This should happen if bigdl/ipex and oneapi versions mismatch, can you confirm this?

**Comment by sriraman2020** [comment] 2024-01-24 09:01
@hkvision 

Actually Torch version 2.1.a0
oneapi version is 2024.0

So it seems to tally

**Comment by MeouSker77** [comment] 2024-01-24 09:14
> ImportError: libsycl.so.6: cannot open shared object file: No such file or directory

please check `intel_extension_for_pytorch` version: `pip list | grep intel_extension_for_pytorch`

`libsycl.so.6` is included in oneapi 2023.2, and it is required by `intel_extension_for_pytorch 2.0`

`intel_extension_for_pytorch 2.1` requires `libsycl.so.7`, which is included in oneapi 2024.0

If you are using `intel_extension_for_pytorch 2.0`, please update it to 2.1: `pip install --pre --upgrade --force-reinstall bigdl-llm[xpu] -f https://developer.intel.com/ipex-whl-stable-xpu`

**Comment by sriraman2020** [comment] 2024-01-24 09:47
@MeouSker77 intel_extension_for_pytorch version is 2.1.10+xpu

**Comment by MeouSker77** [comment] 2024-01-24 09:50
Is that error happened when import `linear_q4_0` ?
If is, try
```
pip uninstall bigdl-core-xe
pip uninstall bigdl-core-xe-21
pip install --pre --upgrade bigdl-core-xe-21
```

**Comment by sriraman2020** [comment] 2024-01-24 09:58
@MeouSker77 Cool, That Worked!! Thanks!

**Comment by jason-dai** [comment] 2024-01-24 14:40
> @MeouSker77 does it work for multi GPU ? We have currently tried it on a single PVC. 1T system

Yes - see distributed [inference](https://github.com/jason-dai/BigDL/tree/main/python/llm/example/GPU/Deepspeed-AutoTP) and [finetuning ](https://github.com/jason-dai/BigDL/tree/main/python/llm/example/GPU/QLoRA-FineTuning) examples.

**Comment by sriraman2020** [comment] 2024-01-30 13:06
@MeouSker77 i tried [inference](https://github.com/jason-dai/BigDL/tree/main/python/llm/example/GPU/Deepspeed-AutoTP) on multi PVC system. bash run_llama2_70b_pvc_1550_1_card.sh
GEt this error 
[1] Uptime: 48.521245 s

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 0 PID 25597 RUNNING AT aia-sdp-pvc-135536
=   KILLED BY SIGNAL: 11 (Segmentation fault)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 1 PID 25598 RUNNING AT aia-sdp-pvc-135536
=   KILLED BY SIGNAL: 11 (Segmentation fault)
===================================================================================
Any idea what could be going wrong?

**Comment by plusbang** [comment] 2024-02-01 03:28
> [0] LIBXSMM_VERSION: main_stable-1.17-3651 (25693763)LIBXSMM WARNING: AMX state allocation in the OS failed! 
> [0] LIBXSMM_TARGET: clx [Intel(R) Xeon(R) Platinum 8480+]
> [0] Registry and code: 13 MB

Hi, if you want to run distributed inference, please first make sure you’ve prepared environment with PyTorch2.1 following [installation instruction](https://bigdl.readthedocs.io/en/latest/doc/LLM/Overview/install_gpu.html#linux). Then please follow the detailed [README](https://github.com/intel-analytics/BigDL/tree/main/python/llm/example/GPU/Deepspeed-AutoTP#example) to run.

P.S. We could not reproduce your error on our machine.

**Comment by sriraman2020** [comment] 2024-02-01 03:51
Issue is resolved. Works now. Thanks for the support. But AMX is still not loading on SDP machine as well, so need to bypass AMX through export.

**Comment by hkvision** [comment] 2024-02-01 10:27
Closing this issue. Feel free to tell us if you have further questions :)

**Closed as completed by hkvision** 2024-02-01 10:27 UTC
Labels: user issue
