### ISSUE TITLE
init_engine(): 'JavaPackage' object is not callable

### ISSUE THREAD

**Issue by lucashu1** [intel-analytics/BigDL#2599] opened 2018-07-19 00:11 UTC
Hi,

I'm trying to use the `DLEstimator` class in a Jupyter notebook via the Python interface. I have Spark 2.3.1 installed, along with BigDL 0.6.0 and Python 3.6. I have a pre-existing JupyterHub infrastructure running in a VM, so I'm trying to use my own Jupyter notebook setup, instead launching the notebooks using the included `jupyter-with-bigdl.sh` script.

Per the [FAQ](https://bigdl-project.github.io/master/#PythonUserGuide/python-faq/), I believe I have all the proper environment variables set, but I'm still getting: `'JavaPackage' object is not callable` when running `init_engine()`.

Here's the code that I'm running:
```
import os
import sys

BIGDL_HOME = '/usr/local/bigdl'

os.environ['BIGDL_HOME'] = BIGDL_HOME

os.environ['BIGDL_JAR_NAME'] = 'bigdl-SPARK_2.3-0.6.0-jar-with-dependencies.jar'
os.environ['BIGDL_JAR'] = BIGDL_HOME + '/lib/' + os.environ['BIGDL_JAR_NAME']

os.environ['BIGDL_PY_ZIP_NAME'] = 'bigdl-0.6.0-python-api.zip'
os.environ['BIGDL_PY_ZIP'] = os.environ['BIGDL_HOME'] + '/lib/' + os.environ['BIGDL_PY_ZIP_NAME']

os.environ['BIGDL_CONF'] = BIGDL_HOME + '/conf/spark-bigdl.conf'

os.environ['PYTHONPATH'] += (':' + os.environ['BIGDL_PY_ZIP'])
sys.path.insert(0, BIGDL_HOME + '/lib/bigdl-0.6.0-python-api.zip')

from bigdl.nn.layer import *
from bigdl.nn.criterion import *
from bigdl.util.common import *
from bigdl.dlframes.dl_classifier import *

from pyspark.sql.types import *
from pyspark.context import SparkContext

sc = SparkContext.getOrCreate(conf=create_spark_conf().setMaster('local[*]'))
sqlContext = SQLContext(sc)

# Init BigDL
init_engine()
```

And the error message that I'm getting:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-cbe6451a1bf3> in <module>()
      3 
      4 # Init BigDL
----> 5 init_engine()

/usr/local/bigdl/lib/bigdl-0.6.0-python-api.zip/bigdl/util/common.py in init_engine(bigdl_type)
    415 
    416 def init_engine(bigdl_type="float"):
--> 417     callBigDlFunc(bigdl_type, "initEngine")
    418     # Spark context is supposed to have been created when init_engine is called
    419     get_spark_context()._jvm.org.apache.spark.bigdl.api.python.BigDLSerDe.initialize()

/usr/local/bigdl/lib/bigdl-0.6.0-python-api.zip/bigdl/util/common.py in callBigDlFunc(bigdl_type, name, *args)
    577     gateway = _get_gateway()
    578     error = Exception("Cannot find function: %s" % name)
--> 579     for jinvoker in JavaCreator.instance(bigdl_type, gateway).value:
    580         # hasattr(jinvoker, name) always return true here,
    581         # so you need to invoke the method to check if it exist or not

/usr/local/bigdl/lib/bigdl-0.6.0-python-api.zip/bigdl/util/common.py in instance(cls, bigdl_type, *args)
     54             with cls._lock:
     55                 if not cls._instance:
---> 56                     cls._instance = cls(bigdl_type, *args)
     57         return cls._instance
     58 

/usr/local/bigdl/lib/bigdl-0.6.0-python-api.zip/bigdl/util/common.py in __init__(self, bigdl_type, gateway)
     91             jclass = getattr(gateway.jvm, creator_class)
     92             if bigdl_type == "float":
---> 93                 self.value.append(getattr(jclass, "ofFloat")())
     94             elif bigdl_type == "double":
     95                 self.value.append(getattr(jclass, "ofDouble")())

TypeError: 'JavaPackage' object is not callable
```

Any thoughts on what else could be going wrong? Is there another environment variable that I missed, or is there some other config step that I'm missing?

If I comment out all the environment variable lines and just run the example code from [here](https://bigdl-project.github.io/master/#PythonUserGuide/run-from-pip/):
```
from bigdl.util.common import *
from pyspark import SparkContext
from bigdl.nn.layer import *
import bigdl.version

# # create sparkcontext with bigdl configuration
sc = SparkContext.getOrCreate(conf=create_spark_conf().setMaster("local[*]"))
init_engine() # prepare the bigdl environment 
bigdl.version.__version__ # Get the current BigDL version
linear = Linear(2, 3) # Try to create a Linear layer
```
everything runs fine, but I'm unable to import `bigdl.dlframes` (so I can't use `DLEstimator`), so I'm not entirely sure what's going on.

Thanks in advance!

**Comment by yiheng** [comment] 2018-07-19 07:30
@megaSpoon please take a look at this.

**Comment by megaSpoon** [comment] 2018-07-19 22:33
@lucashu1 I'm looking into this issue. Will give a feedback later!

**Comment by lucashu1** [comment] 2018-07-19 22:43
Thanks @megaSpoon! Look forward to hearing back.

**Comment by megaSpoon** [comment] 2018-07-20 00:59
@lucashu1 I reproduced your error. It seems that you already using pip install bigdl=0.6.0 to install the python package.
One quick workaround is remove all the environment variable setup lines. Instead of importing dl_classifier from bigdl.dlframes, using `from bigdl.models.ml_pipeline.dl_classifier import *`. These two API files are the same but I can find the latter one in the python's dist-packages while the "dlframes" folder is non-existent. I will propose an issue for it. Thanks for what you found!

**Comment by megaSpoon** [comment] 2018-07-20 01:30
The way you set up the environment variables are not viable. It's not that simple to translate what variables in jupyter-with-bigdl.sh into the python script. Since some of those variables are not environment variables, instead  are alias for the file paths to be necessarily passed to the Pyspark script.

**Comment by megaSpoon** [comment] 2018-07-20 08:33
The dlframes not found issue was fixed in our next release. Check it out. https://github.com/intel-analytics/BigDL/pull/2588

**Closed by megaSpoon** 2018-07-20 08:33 UTC
