### ISSUE TITLE
Method "apply" of class BytesToBGRImg will return the Iterator which has SAME elements

### ISSUE THREAD

**Issue by Zen-w** [intel-analytics/BigDL#2995] opened 2020-03-02 18:03 UTC
This is a part of class `BytesToBGRImg` in .../dataset/image/BytesToBGRImg.scala:
```scala
private val buffer = new LabeledBGRImage()
override def apply(prev: Iterator[ByteRecord]): Iterator[LabeledBGRImage] = {
    prev.map(rawData => {
      buffer.copy(getImgData(rawData, resizeW, resizeH), normalize).setLabel(rawData.label)
    })
  }
```
And I use its method "apply" to transform `Iterator[ByteRecord]` to `Iterator[LabeledBGRImage]`, like this:
```scala
val BGRImgs = new BytesToBGRImg(1,32,32).apply(byteRecords)
```
But the result is that all the elements of `BGRImgs` is identical, I can confirm that the elements of `byteRecords` is not same.
I suspect that all the elements of `prev` use the __same__ buffer in memory instead of __new__ .
Therefore, in `prev.map(...)`, the subsequent `rawData` will **overwrite** the foregoing `rawData`, which leads to that `Iterator[LabeledBGRImage]` will has identical `LabeledBGRImage`s.

I don't determine whether it is a Bug or not. (I am a newbie...)
And if not, can I think it is wrong to use `.apply()` like above?

Thank you.

**Comment by helenlly** [comment] 2020-03-04 03:02
DD, pls help to check

**Comment by helenlly** [comment] 2020-03-04 06:03
@Zen-w ,we will try to reproduce and see if it is a bug or usage issue, thanks

**Comment by Zen-w** [comment] 2020-03-04 06:11
@helenlly , thanks reply, looking forward to your results

**Comment by qiuxin2012** [comment] 2020-03-04 08:13
@Zen-w It's not a bug, we use a output buffer in the BytesToBGRImg to avoid GC.

As you see, its result is a `Iterator[LabeledBGRImage]`, if you use a foreach loop to iterate the iterator, the LabeledBGRImage will be different from each other in their loop.

If you call `BGRImgs.toArray` to get a `Array[LabeledBGRImage]`, all the elements will be the output buffer.

**Comment by Zen-w** [comment] 2020-03-04 09:33
@qiuxin2012 Thanks, I did find the problem is `toArray`.

By the way, can I understand that you said "avoid GC" meaning to use `val buffer = new LabeledBGRImage()` **once**, instead of `new LabeledBGRImage()` in `prev.map(...)`, in order to improve performance ?

**Comment by qiuxin2012** [comment] 2020-03-06 01:10
@Zen-w Yes, just create `LabeledBGRImage` once. I will close this issue.

**Closed by qiuxin2012** 2020-03-06 01:10 UTC
