### ISSUE TITLE
[Nano]Keras sequential API calls parent method for fit() on model object

### ISSUE THREAD

**Issue by nushrathumaira** [intel-analytics/BigDL#4756] opened 2022-06-04 17:51 UTC
I am getting started with BigDL and first example I tried is BigDL-nano tensorflow training.
I ran this example for multi instance training [https://bigdl.readthedocs.io/en/latest/doc/Nano/QuickStart/tensorflow_train.html](url)

Error message:
`2022-06-04 13:24:46.087913: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-06-04 13:24:46.697006: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 14614 MB memory:  -> device: 0, name: Tesla V100-PCIE-16GB, pci bus id: 0000:d8:00.0, compute capability: 7.0
<bigdl.nano.tf.keras.Sequential.Sequential object at 0x149ea3afd790>
Traceback (most recent call last):
  File "keras_example.py", line 20, in <module>
    model.fit(x_train, y_train, epochs=5, num_processes=4,backend="multiprocessing")
TypeError: fit() got an unexpected keyword argument 'num_processes'
`
I think it is calling the fit method of parent, tf.keras.model.fit

I am running BigDL-nano inside conda on cluster hosted by my university. environment variable OMP_NUM_THREADS prints 4.

**Comment by yangw1234** [comment] 2022-06-05 01:29
Hi @nushrathumaira , thank you for trying out Nano.

May I ask which version of bigdl-nano are you using?

**Comment by nushrathumaira** [comment] 2022-06-05 01:33
> Hi @nushrathumaira , thank you for trying out Nano.
> 
> May I ask which version of bigdl-nano are you using?

I am using bigdl-nano 2.0.0 installed through pip

**Comment by nushrathumaira** [comment] 2022-06-05 02:56
> > > Hi @nushrathumaira , thank you for trying out Nano.
> > > May I ask which version of bigdl-nano are you using?
> > 
> > 
> > I am using bigdl-nano 2.0.0 installed through pip
> 
> We changed the signature lately. Would you mind trying our nightly version by running `pip install --pre bigdl-nano`

Following your advice, I upgraded the bigdl completely instead of bigdl-nano with `pip install --pre --upgrage bigdl`
which updated the tensorflow-gpu that I installed separately. However I got an error using tf.keras.datasets.

I know nano multi instance training does not support tensorflow dataset.from_generators, numpy_function, py_function.
I also tried tensorflow-datasets which gave `AttributeError: module 'distutils' has no attribute 'version'`
Which dataset API do you suggest. Thanks

`****************************Usage Error************************
x must be a tf.data.Dataset for multi-process training


****************************Call Stack*************************
Traceback (most recent call last):
  File "keras_example.py", line 20, in <module>
    model.fit(x_train, y_train, epochs=5, num_processes=4,backend="multiprocessing")
  File "/home/nhumair/.conda/envs/bigdl/lib/python3.7/site-packages/bigdl/nano/tf/keras/training_utils.py", line 90, in fit
    invalidInputError(isinstance(x, (tf.compat.v1.data.Dataset, tf.data.Dataset)), msg)
  File "/home/nhumair/.conda/envs/bigdl/lib/python3.7/site-packages/bigdl/nano/utils/log4Error.py", line 32, in invalidInputError
    raise RuntimeError(errMsg)
RuntimeError: x must be a tf.data.Dataset for multi-process training
`

**Comment by yangw1234** [comment] 2022-06-06 01:12
hi @nushrathumaira , by `tf.data.dataset` we mean the data pipeline described [here](https://www.tensorflow.org/guide/data). `tf.keras.datasets` are essentially numpy ndarrays which we have not support yet.

The datasets defined in package `tensorflow_datasets` are instances of `tf.data.dataset` and should work.

 For the `AttributeError: module 'distutils' has no attribute 'version'` issue, it looks like relating to the recent setuptools upgrade and you could try using setuptools==58.0.4. And would you mind posting the packages versions in your environment so that we can reproduce on our side?

**Comment by nushrathumaira** [comment] 2022-06-11 04:00
> hi @nushrathumaira , by `tf.data.dataset` we mean the data pipeline described [here](https://www.tensorflow.org/guide/data). `tf.keras.datasets` are essentially numpy ndarrays which we have not support yet.
> 
> The datasets defined in package `tensorflow_datasets` are instances of `tf.data.dataset` and should work.
> 
> For the `AttributeError: module 'distutils' has no attribute 'version'` issue, it looks like relating to the recent setuptools upgrade and you could try using setuptools==58.0.4. And would you mind posting the packages versions in your environment so that we can reproduce on our side?

I apologize for the late reply, while navigating around conda environment and system settings, some more errors were created.  Specially I realized that some env variables like LD_PRELOAD and NANO-TF_-INTEROPS were not set properly, which made the cuda libraries and GPU not work properly. While with CPU, num_processes matched with number of cores used worked for this multi instance reply.  

So the original problem of 'fit' method seem to have been solved somehow. Should I open a new issue if the issues related to system configuration persists?
FYI- I used `tf.data.dataset ` and didn't use `tensorflow_datasets` or downgraded setuptools.

**Comment by jason-dai** [comment] 2022-06-11 10:11
> > hi @nushrathumaira , by `tf.data.dataset` we mean the data pipeline described [here](https://www.tensorflow.org/guide/data). `tf.keras.datasets` are essentially numpy ndarrays which we have not support yet.
> > The datasets defined in package `tensorflow_datasets` are instances of `tf.data.dataset` and should work.
> > For the `AttributeError: module 'distutils' has no attribute 'version'` issue, it looks like relating to the recent setuptools upgrade and you could try using setuptools==58.0.4. And would you mind posting the packages versions in your environment so that we can reproduce on our side?
> 
> I apologize for the late reply, while navigating around conda environment and system settings, some more errors were created. Specially I realized that some env variables like LD_PRELOAD and NANO-TF_-INTEROPS were not set properly, which made the cuda libraries and GPU not work properly. While with CPU, num_processes matched with number of cores used worked for this multi instance reply.
> 
> So the original problem of 'fit' method seem to have been solved somehow. Should I open a new issue if the issues related to system configuration persists? FYI- I used `tf.data.dataset ` and didn't use `tensorflow_datasets` or downgraded setuptools.

Yes, you may close this one if it is solved, and then open a new PR. @nushrathumaira

**Closed** 2022-06-11 16:20 UTC
Labels: user issue
