### ISSUE TITLE
pip installation has issue for Linux 

### ISSUE THREAD

**Issue by Fred-cell** [intel-analytics/BigDL#9522] opened 2023-11-23 12:36 UTC
why downloads so many versions for pip installation as below:
![image](https://github.com/intel-analytics/BigDL/assets/99886928/450ae672-b9d6-4075-96ec-0dbda4d2967b)
![image](https://github.com/intel-analytics/BigDL/assets/99886928/8182f077-29cd-4447-a943-a2a804f9c088)

**Comment by hkvision** [comment] 2023-11-24 02:13
Synced offline, the issue is caused by not using `pip install --pre --upgrade bigdl-llm[xpu] -f https://developer.intel.com/ipex-whl-stable-xpu`.

Fred is using the aliyun mirror because the above command is extremely slow last night. It works fine this morning.

The issue may now be can ipex be installed with other mirrors?

**Comment by hkvision** [comment] 2023-11-24 10:59
Explanation of `why downloads so many versions`:
- First of all, ipex and specific torch versions are not released on pypi: https://pypi.org/project/intel-extension-for-pytorch/#history and thus they are not available on mirrors like aliyun or tsinghua. They can only be downloaded from here: https://developer.intel.com/ipex-whl-stable-xpu i.e. http://ec2-52-27-27-201.us-west-2.compute.amazonaws.com/ipex-release.php?device=xpu&repo=us&release=stable
- For pip, as shown in the info below, it will try to find a version that can satisfy the 'xpu' dependencies, and it will find the versions from the most recent to the oldest until it finds a version that can satisfy the dependencies.
![image](https://github.com/intel-analytics/BigDL/assets/21994046/6bae3b04-423e-43cb-ad39-f50b7535e327)
But since no dependency can be found on other mirrors, it will attempt all existing versions and fail. Under the case it fails, it will install the last version it finds (i.e. 0819 one)
![image](https://github.com/intel-analytics/BigDL/assets/21994046/89d0dec8-aa15-4a7c-b587-3e06fe30d28e)
- This is just kind of retrying policy of pip, which has nothing to do with bigdl. If you install other packages with unsatisfied dependencies, you will observe the same behavior.
- If you find network issues when installing ipex, you can download the whl first and install locally, for example from https://intel-extension-for-pytorch.s3.amazonaws.com/ipex_stable/xpu/intel_extension_for_pytorch-2.0.110%2Bxpu-cp39-cp39-linux_x86_64.whl

**Comment by hkvision** [comment] 2023-11-29 06:14
Will polish the documentation to better guide users to install target torch/ipex versions.

**Comment by hkvision** [comment] 2023-12-12 06:15
We have updated our doc here: https://github.com/intel-analytics/BigDL/pull/9583
Closing this issue.

**Closed by hkvision** 2023-12-12 06:15 UTC
Labels: user issue
